spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: umutserdar
      port: 27017
      host: localhost
server:
  port: 8081

